using CMS.API.Models;
using CMS.API.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CMS.API.Controllers;

[ApiController]
[Route("api/course-groups")]
[Produces("application/json")]
public class CourseGroupsController : ControllerBase
{
    private readonly ICourseGroupRepository _repository;

    public CourseGroupsController(ICourseGroupRepository repository) => _repository = repository;

    /// <summary>List all course groups.</summary>
    [HttpGet]
    public async Task<ActionResult<IEnumerable<CourseGroup>>> GetAll()
        => Ok(await _repository.GetAllAsync());

    /// <summary>Filtered search (keyword on Description).</summary>
    [HttpPost("query")]
    public async Task<ActionResult<IEnumerable<CourseGroup>>> Query([FromBody] CourseGroupQuery query)
        => Ok(await _repository.QueryAsync(query ?? new CourseGroupQuery()));

    /// <summary>Get a single course group by pkid.</summary>
    [HttpGet("{id}")]
    public async Task<ActionResult<CourseGroup>> GetById(short id)
    {
        var group = await _repository.GetByIdAsync(id);
        return group is null ? NotFound() : Ok(group);
    }

    /// <summary>Create a course group (pkid generated by IDENTITY).</summary>
    [HttpPost]
    public async Task<ActionResult<CourseGroup>> Create([FromBody] CourseGroupRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Description))
            return BadRequest("Description is required.");

        var created = await _repository.CreateAsync(request);
        return CreatedAtAction(nameof(GetById), new { id = created.Pkid }, created);
    }

    /// <summary>Update a course group (pkid taken from the body).</summary>
    [HttpPut]
    public async Task<IActionResult> Update([FromBody] CourseGroupRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Description))
            return BadRequest("Description is required.");
        if (!await _repository.ExistsAsync(request.Pkid))
            return NotFound();

        await _repository.UpdateAsync(request);
        return NoContent();
    }

    /// <summary>Delete a course group by pkid.</summary>
    [HttpDelete("{id}")]
    public async Task<IActionResult> Delete(short id)
        => await _repository.DeleteAsync(id) ? NoContent() : NotFound();
}
